# Quality Control -------------------------------------------------------------
FASTQ_SCREEN: src/fastq_screen.conf

# Alignment -------------------------------------------------------------------
# path to a bowtie2 index
GENOME: testdata/hg38_chr1
FASTA: testdata/Homo_sapiens.GRCh38.dna_rm.chromosome.1.fa.gz
GENES: genes/hg38_refseq_genes.bed

# Peak Calling ----------------------------------------------------------------

#should we use IGG for peak calling or not?
USEIGG: true

# how is IgG spelled in the filename, eg: "IgG"  for file "G1_IgG_Kasumi_S25_R2.fastq.gz"
IGG: IgG

CSIZES: testdata/hg38.chrom.sizes

# Peak Processing
# the number of times a peak must appear across biological replicates (within one condition) to be considered a consensus peak

N_INTERSECTS: 2

