#should we use IGG for peak calling or not? 
USEIGG: true
#  how is IgG spelled in the filename, eg: "IgG"  for file "G1_IgG_Kasumi_S25_R2.fastq.gz"
IGG: "IgG"
CSIZES:
    - "/home/groups/MaxsonLab/indices/mm10/mm10.chrom.sizes"
GENOME:
    - "/home/groups/MaxsonLab/indices/mm10/mm10"
GENES: 
    - "genes/mm10_refseq_genes.bed"
FASTQ_SCREEN: "src/fastq_screen.conf"
FASTA: "/home/groups/MaxsonLab/indices/mm10/mm10.fa"
N_INTERSECTS: 2
