FASTQDIR:
    - "data/raw"
FASTQEXT:
    - ".fastq.gz"
CSIZES:
    - "/home/groups/hoolock2/u0/genomes/ucsc/hg38/hg38.known.chrom.sizes"
GENOME:
    - "/home/groups/MaxsonLab/indices/GRch38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index"
BOWTIE2:
    HG38:
        - "/home/groups/MaxsonLab/indices/GRch38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index"
    MM10:
        - "/home/groups/MaxsonLab/indices/mm10/mm10"
    ECOLI:
        - "/home/groups/MaxsonLab/indices/ecoli_EB1/genome"
    MYCO:
        - "/home/groups/MaxsonLab/indices/mycoplasma_index/mycoplasma"
